notifications:
  email: false

language: python

python: 3.6

addons:
  hosts:
    - registry.localhost
    - registry-hosted.localhost
    - registry-proxy.localhost

sudo: true

stages:
  - test

services:
  - docker

install:
  - docker-compose build
  - docker-compose up -d

jobs:
  include:
    # Test dockerhub mirror
    - stage: test
      script:
        - docker pull registry.localhost/library/nginx:latest
        - curl -k --write-out %{http_code} --silent --output /dev/null registry-proxy.localhost/v2/library/nginx/manifests/latest | grep 200
        - "! curl -k --write-out %{http_code} --silent --output /dev/null registry-hosted.localhost/v2/library/nginx/manifests/latest | grep 200"

    # Test private registry
    - stage: test
      before_script:
        - echo -e "FROM alpine:latest\nRUN echo '123' > test.txt\n" > Dockerfile
        - docker build -t registry.localhost/mytestimage:latest .
      script:
        - docker push registry.localhost/mytestimage:latest
        - docker rmi registry.localhost/mytestimage:latest
        - docker pull registry.localhost/mytestimage:latest
        - curl -k --write-out %{http_code} --silent --output /dev/null registry-hosted.localhost/v2/mytestimage/manifests/latest | grep 200
        - "! curl -k --write-out %{http_code} --silent --output /dev/null registry-proxy.localhost/v2/mytestimage/manifests/latest | grep 200"

    # Test basic auth
    - stage: test
      env:
        - ENABLE_AUTH=true
      before_install:
        - echo 'admin:$apr1$wyZ6v/sB$Zq4FWr9Gc97OdB8HuX/QO/' > nginx/htpasswd  # hunter2
      script:
        - "! docker pull registry.localhost/library/nginx:latest"
        - docker login --username=admin --password=hunter2
        - docker pull registry.localhost/library/nginx:latest
